language: java
jdk: openjdk8
jobs:
  include:
    - stage: detekt
      script: ./gradlew detekt
    - stage: build
      script: ./gradlew assemble
    - stage: unit test
      script: ./gradlew test
notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
