dist: trusty
language: java
jdk: oraclejdk8
jobs:
  include:
    - stage: build
      script: ./gradlew assemble
    - stage: unit test
      script: ./gradlew test
    - stage: detekt
      script: ./gradlew detekt
notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
